### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by mattjbray** [haskell-servant/servant-elm#44]
Work is under way at https://github.com/mattjbray/servant-elm/compare/019-tostring

**Comment by domenkozar** [comment]
There is a PR up: https://github.com/mattjbray/servant-elm/pull/45

**Comment by gege251** [comment]
I just noticed that the NoRedInk fork https://github.com/NoRedInk/servant-elm seems to be more active, haven't tried it yet but it should work with Elm 0.19. They also have a fork of elm-export which is the main dependency of this package.

**Comment by andys8** [comment]
It was updated. https://github.com/haskell-servant/servant-elm/blob/master/CHANGELOG.md#0600
#49 

This ticket can be closed.
