### ISSUE TITLE
Transfer repo to @haskell-servant

### ISSUE THREAD

**Issue by mattjbray** [haskell-servant/servant-elm#48]
Continued from #45.

cc @alpmestan @domenkozar @k-bx 

It seems that to transfer ownership I need permission to create repos in the @haskell-servant org.

I see three options:
1. Add me to the @haskell-servant org, temporarily or otherwise, and I'll transfer the repo;
2. I can transfer the repo to the user account of someone with access, who can then transfer the repo from their account to @haskell-servant; or
3. Someone with access can fork this repo into @haskell-servant and I'll put a note here that this repo is deprecated (probably not ideal).

How should we proceed?

**Comment by domenkozar** [comment]
I'd say it's best if you add @alpmestan as admin to your repo and he can do the transfer.

**Comment by mattjbray** [comment]
I don't think it's possible to add an admin to a personal repo.

**Comment by domenkozar** [comment]
Always forget that part :) Will wait for @alpmestan to comment what he prefers to do.

**Comment by alpmestan** [comment]
I personally like 3. because it'll leave a trace that the repo was originally yours, it's a (cheap) way to give credits. I'm not opposed to 1. or 2. though.

**Comment by mattjbray** [comment]
Thanks for thinking about giving me credit :) but I think 1 or 2 would be more solid since Github will handle redirects so less chance of people getting the wrong repo, issues and PRs will move over, etc.

If you're not opposed I think 1 will be easiest. Are you able to temporarily add me to the haskell-servant org and give me repo create permissions?

**Comment by alpmestan** [comment]
OK, let's go with 1 then. Invitation to join haskell-servant sent.

**Comment by mattjbray** [comment]
@alpmestan I didn't receive any invitation yet. Just tried to transfer the repo again and I don't have the repo create permission in haskell-servant.

**Comment by alpmestan** [comment]
Should be good now.

![mattjbray](https://user-images.githubusercontent.com/119323/54871297-126a8900-4db2-11e9-9633-fc289cc22eb4.png)

Not sure what happened earlier.

**Comment by mattjbray** [comment]
It's done!
