### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by k-bx** [haskell-servant/servant-elm#66]
subj

See also: https://discourse.haskell.org/t/looking-for-maintainers-hedis-and-servant-elm/4616

**Comment by ilyakooo0** [comment]
I can become a maintainer

**Comment by k-bx** [comment]
@ilyakooo0 what's your hackage username?

**Comment by ilyakooo0** [comment]
@k-bx https://hackage.haskell.org/user/iko

**Comment by k-bx** [comment]
Just realised I don't have settings access to this repo.

@jkarni are you the right person to reach out to?

**Comment by jkarni** [comment]
@k-bx added @ilyakooo0 to the github repo. I don't have access to the hackage package though - you, @mattjbray and @domenkozar do.

**Comment by k-bx** [comment]
Added user iko as a hackage maintainer. Thanks, everyone!
