### ISSUE TITLE
Request to release version 0.7.3 that includes fix of broken tests

### ISSUE THREAD

**Issue by anddani** [haskell-servant/servant-elm#67]
There is a fix for an issue where some tests failed on version 0.7.2: https://github.com/haskell-servant/servant-elm/issues/62. However, there is no release tag with this change yet.

These failed tests breaks builds when using nix as tests are run in the build step resulting in this library being considered "broken" in nixpkgs. This also seem to affect stackage as mentioned here: https://github.com/commercialhaskell/stackage/issues/5988

Would it make sense to create a new version on this commit?

**Comment by ilyakooo0** [comment]
Done: https://hackage.haskell.org/package/servant-elm-0.7.3
